- task: AppCenterTest@1
  inputs:
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'appium'
    credentialsOption: 'serviceEndpoint'
    localeOption: 'en_US'
