trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo 'Hello, Azure Pipelines!'
    displayName: 'Print a message'

  # Add your build and deployment steps here
